In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [27]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "movies.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "abdallahwagih/movies",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipython-input-426988513.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/abdallahwagih/movies?dataset_version_number=1&file_name=movies.csv...

100%|██████████| 5.13M/5.13M [00:01<00:00, 3.54MB/s]

Extracting zip of movies.csv...

First 5 records:    index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction
1      1  300000000                  Adventure Fantasy Action
2      2  245000000                    Action Adventure Crime
3      3  250000000               Action Crime Drama Thriller
4      4  260000000          Action Adventure Science Fiction

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995
1  http://disney.go.com/disneypictures/pirates/     285
2   http://www.sonypictures.com/movies/spectre/  206647
3            http://www.thedarkknightrises.com/   49026
4          http://movies.disney.com/john-carter   49529

                                            keywords original_language  \
0  culture clash future space war space colony so...                en
1  ocean drug abuse exotic island east india trad...                en
2         spy based on novel secret agent sequel mi6                en
3  dc comics crime fighter terrorist secret ident...                en
4  based on novel mars medallion space travel pri...                en

                             original_title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0
3  Following the death of District Attorney Harve...  112.312950  ...   165.0
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released
1           [{"iso_639_1": "en", "name": "English"}]  Released
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released
3           [{"iso_639_1": "en", "name": "English"}]  Released
4           [{"iso_639_1": "en", "name": "English"}]  Released

                                          tagline  \
0                     Enter the World of Pandora.
1  At the end of the world, the adventure begins.
2                           A Plan No One Escapes
3                                 The Legend Ends
4            Lost in our world, found in another.

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800
1  Pirates of the Caribbean: At World's End          6.9       4500
2                                   Spectre          6.3       4466
3                     The Dark Knight Rises          7.6       9106
4                               John Carter          6.1       2124

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...
1  Johnny Depp Orlando Bloom Keira Knightley Stel...
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...
3  Christian Bale Michael Caine Gary Oldman Anne ...
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...

                                                crew           director
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton

[5 rows x 24 columns]

In [28]:
df.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [29]:
df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [15]:
# feature selection
# genre , rating, language, title, overview,

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [31]:
df.shape

(4803, 24)

In [32]:
df.drop_duplicates().reset_index(drop=True)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [33]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.isnull().sum()

Unnamed: 0          0
URLs                0
Year_Released     111
Title               0
IMDB Ids          120
Cast                0
Plot_Summary        0
Review              1
Genre               0
Released Date       0
Plot Keywords       0
Duration            0
Age of content    111
dtype: int64

In [34]:
df.columns

Index(['index', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew', 'director'],
      dtype='object')

In [35]:
df = df[['original_title', 'overview','genres','cast','director','tagline', 'production_companies', 'original_language','runtime',]]

In [36]:
df.head()

,original_title,overview,genres,cast,director,tagline,production_companies,original_language,runtime
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron,Enter the World of Pandora.,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",en,162.0
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski,"At the end of the world, the adventure begins.","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",en,169.0
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,Sam Mendes,A Plan No One Escapes,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",en,148.0
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,Christian Bale Michael Caine Gary Oldman Anne ...,Christopher Nolan,The Legend Ends,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",en,165.0
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,Taylor Kitsch Lynn Collins Samantha Morton Wil...,Andrew Stanton,"Lost in our world, found in another.","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",en,132.0

In [37]:
df.isnull().sum()

original_title            0
overview                  3
genres                   28
cast                     43
director                 30
tagline                 844
production_companies      0
original_language         0
runtime                   2
dtype: int64

In [41]:
df['overview'] = df['overview'].fillna('')
df['tagline'] = df['tagline'].fillna('')
df['cast'] = df['cast'].fillna('')
df['director'] = df['director'].fillna('unknown_director')
df['genres'] = df['genres'].fillna('unknown')
df['runtime'] = df['runtime'].fillna(df['runtime'].median())

In [42]:
df.isnull().sum()

original_title          0
overview                0
genres                  0
cast                    0
director                0
tagline                 0
production_companies    0
original_language       0
runtime                 0
dtype: int64

In [43]:
df ['tags'] = df['overview']+ " " + df['genres'] +" "+ df ['tagline']

In [44]:
df.head()

,original_title,overview,genres,cast,director,tagline,production_companies,original_language,runtime,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron,Enter the World of Pandora.,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",en,162.0,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski,"At the end of the world, the adventure begins.","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",en,169.0,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,Sam Mendes,A Plan No One Escapes,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",en,148.0,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,Christian Bale Michael Caine Gary Oldman Anne ...,Christopher Nolan,The Legend Ends,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",en,165.0,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,Taylor Kitsch Lynn Collins Samantha Morton Wil...,Andrew Stanton,"Lost in our world, found in another.","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",en,132.0,"John Carter is a war-weary, former military ca..."

In [45]:
df.iloc[0]['tags']

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction Enter the World of Pandora.'

### Preprocessinig (NLP)

In [46]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [47]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [48]:
stopwords = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [50]:
def PreProcess(text):
  text = str(text).lower()
  text = re.sub(r'[^a-zA-Z\s]','',text)

  words = text.split()
  # remove stopwords
  words = [word for word in words if word not in stopwords]
  # lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return ' '.join(words)

In [51]:
# applying preprocessing on 'tags' column
df['tags'] = df['tags'].apply(PreProcess)

In [52]:
df.head()

,original_title,overview,genres,cast,director,tagline,production_companies,original_language,runtime,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron,Enter the World of Pandora.,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",en,162.0,nd century paraplegic marine dispatched moon p...
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski,"At the end of the world, the adventure begins.","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",en,169.0,captain barbossa long believed dead come back ...
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,Sam Mendes,A Plan No One Escapes,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",en,148.0,cryptic message bond past sends trail uncover ...
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,Christian Bale Michael Caine Gary Oldman Anne ...,Christopher Nolan,The Legend Ends,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",en,165.0,following death district attorney harvey dent ...
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,Taylor Kitsch Lynn Collins Samantha Morton Wil...,Andrew Stanton,"Lost in our world, found in another.","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",en,132.0,john carter warweary former military captain w...

### Word Embeddings

In [53]:
df = df.reset_index(drop=True)

In [58]:
df.rename(columns={'original_title': 'title'}, inplace=True)

In [60]:
indices = pd.Series(df.index, index = df['title']).drop_duplicates()

In [61]:
indices

title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [65]:
tfidf = TfidfVectorizer(max_features=5000,ngram_range=(1,2),stop_words='english')

In [66]:
tfidf_mat = tfidf.fit_transform(df['tags'])

In [67]:
tfidf_mat

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 132062 stored elements and shape (4803, 5000)>

### Cosine Similarity

In [68]:
from sklearn.metrics.pairwise import cosine_similarity

In [70]:
def recommend(title, n=10):
  if title not in indices:
    return ['movie not found!']

  idx = indices[title]
  similarity = cosine_similarity(tfidf_mat[idx], tfidf_mat).flatten()
  similarity_idx = similarity.argsort()[::-1][1:n+1]
  return df.iloc[similarity_idx]['title']

In [71]:
df.head()

,title,overview,genres,cast,director,tagline,production_companies,original_language,runtime,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron,Enter the World of Pandora.,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",en,162.0,nd century paraplegic marine dispatched moon p...
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski,"At the end of the world, the adventure begins.","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",en,169.0,captain barbossa long believed dead come back ...
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,Sam Mendes,A Plan No One Escapes,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",en,148.0,cryptic message bond past sends trail uncover ...
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,Christian Bale Michael Caine Gary Oldman Anne ...,Christopher Nolan,The Legend Ends,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",en,165.0,following death district attorney harvey dent ...
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,Taylor Kitsch Lynn Collins Samantha Morton Wil...,Andrew Stanton,"Lost in our world, found in another.","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",en,132.0,john carter warweary former military captain w...

In [73]:
recommend('John Carter')

1254                             Get Carter
4161            The Marine 4: Moving Target
91             Independence Day: Resurgence
256                               Allegiant
2966                  2001: A Space Odyssey
581                 Star Trek: Insurrection
85      Captain America: The Winter Soldier
169      Captain America: The First Avenger
127                      Mad Max: Fury Road
473                           Mars Attacks!
Name: title, dtype: object

In [76]:
recommend('Spectre', 5)

1343    Never Say Never Again
3162              Thunderball
4071    From Russia with Love
11          Quantum of Solace
1200     The Living Daylights
Name: title, dtype: object